export const genres = [
  { key: 'All', category: 'All' },
  { key: 'Documentary', category: 'Documentary' },
  { key: 'Comedy', category: 'Comedy' },
  { key: 'Horror', category: 'Horror' },
  { key: 'Crime', category: 'Crime' },
  { key: 'Cartoon', category: 'Cartoon' },
  { key: 'Fantasy', category: 'Fantasy' },
  { key: 'Drama', category: 'Drama' },
  { key: 'Romance', category: 'Romance' },
  { key: 'Animation', category: 'Animation' },
  { key: 'Adventure', category: 'Adventure' },
  { key: 'Science Fiction', category: 'Science Fiction' },
  { key: 'Action', category: 'Action' },
];
