export const genres = [
  { key: 1, category: 'All' },
  { key: 2, category: 'Documentary' },
  { key: 3, category: 'Comedy' },
  { key: 4, category: 'Horror' },
  { key: 5, category: 'Crime' },
  { key: 6, category: 'Cartoon' },
  { key: 7, category: 'Fantasy' },
  { key: 8, category: 'Drama' },
  { key: 9, category: 'Romance' },
  { key: 10, category: 'Animation' },
  { key: 11, category: 'Adventure' },
  { key: 12, category: 'Science Fiction' },
  { key: 13, category: 'Action' },
];
