export const ActionTypes = {
  HAS_ERROR: 'HAS_ERROR',
  LOADING: 'LOADING',
  GET_MOVIES_LIST: 'GET_MOVIES_LIST',
  GET_MOVIE_BY_ID: 'GET_MOVIE_BY_ID',
  ADD_NEW_MOVIE: 'ADD_NEW_MOVIE',
  DELETE_MOVIE: 'DELETE_MOVIE',
  UPDATE_MOVIE_BY_ID: 'UPDATE_MOVIE_BY_ID',
  SORT_BY: 'SORT_BY',
  SEARCH_MOVIE: 'SEARCH_MOVIE',
  SET_CURRENT_USER: 'SET_CURRENT_USER',
};
